events {}

http {
    server {
        listen 8080;

        # Web principal (Python)
        location / {
            proxy_pass http://backend_telegram:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Grafana
        location /grafana/ {
            # Al quitar la barra final, Nginx envía la ruta /grafana/ tal cual a Grafana
            proxy_pass http://grafana:3000;
            proxy_set_header Host $http_host;
            # Evita que Grafana nos redirija a localhost
            proxy_redirect http://localhost:3000/grafana/ /grafana/;
            proxy_redirect http://localhost/grafana/ /grafana/;
        }

        # RabbitMQ
        location /rabbitmq/ {
            proxy_pass http://rabbitmq:15672;
            # Inyectamos credenciales guest:guest automáticamente para saltar el login
            proxy_set_header Authorization "Basic Z3Vlc3Q6Z3Vlc3Q=";
        }
    }
}
