global:
  scrape_interval: 15s

scrape_configs:
  # Monitorizamos el Backend Flask
  - job_name: 'backend_flask'
    static_configs:
      - targets: ['backend_telegram:9091']

  # Monitorizamos el Worker
  - job_name: 'worker'
    static_configs:
      - targets: ['worker:9092']

  # Prometheus se monitoriza a sí mismo (Buenas práctica)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
