{
 "title": "TFG Observabilidad Total",
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Mensajes Procesados",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(worker_messages_total)" }
   ]
  },
  {
   "title": "Uso CPU Raspberry",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode='idle'}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "Consumo de RAM",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "100 * (1 - ((node_memory_MemFree_bytes + node_memory_Cached_bytes + node_memory_Buffers_bytes) / node_memory_MemTotal_bytes))"
    }
   ]
  },
  {
   "title": "Latencia del Worker (Segundos)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(worker_processing_seconds_sum[1m]) / rate(worker_processing_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "Peticiones HTTP a Flask (Rate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(flask_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Consola de Logs en Vivo (Contenedores)",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{container=~\".+\"}"
    }
   ]
  }
 ]
}